spring:
  r2dbc:
    url: r2dbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:orders}
    username: ${MYSQL_USER:user}
    password: ${MYSQL_PASSWORD:secret123}

logging:
  level:
      org:
        springframework:
          r2dbc: DEBUG
server:
  port: 8080