logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG
spring:
  r2dbc:
    url: r2dbc:mysql://${MYSQL_HOST:localhost}:3306/${MYSQL_DATABASE:orders}
    username: ${MYSQL_USER:user}
    password: ${MYSQL_PASSWORD:secret123}
